INSERT INTO SAR_AUTHORITY (NAME) VALUES ('ADMIN');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('USER');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('PROVIDER');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('CUSTOMER');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('DELIVER');
INSERT INTO SAR_USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED) VALUES (NEXTVAL('USER_SEQ'),'mblagui', 'admin', 'Mhamed', 'Blagui', 'mhamed.blagui88@gmail.com', 1);
INSERT INTO SAR_USER_AUTHORITY (USER_ID , AUTHORITY_NAME) VALUES (1,'ADMIN');