INSERT INTO SARBINI.SAR_AUTHORITY (NAME) VALUES ('ADMIN');
INSERT INTO SARBINI.SAR_AUTHORITY (NAME) VALUES ('USER');
INSERT INTO SARBINI.SAR_AUTHORITY (NAME) VALUES ('PROVIDER');
INSERT INTO SARBINI.SAR_AUTHORITY (NAME) VALUES ('CUSTOMER');
INSERT INTO SARBINI.SAR_AUTHORITY (NAME) VALUES ('DELIVER');
INSERT INTO SARBINI.SAR_USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED) VALUES (NEXTVAL('SARBINI.USER_SEQ'),'mblagui', 'admin', 'Mhamed', 'Blagui', 'mhamed.blagui88@gmail.com', 1);
INSERT INTO SARBINI.SAR_USER_AUTHORITY (USER_ID , AUTHORITY_NAME) VALUES (1,'ADMIN');